import { CharacterFormData } from "./charactersTypes";

export const defaultCharacterFormData: CharacterFormData = {
  name: "",
  mode: "classed",
  subPronoun: "",
  objPronoun: "",
  portrait: "",
  age: 0,
  species: "Human",
  background: "Soldier",
  profession: "Warrior",
  subProfession: "",
  affinity: [],
  selectedFeats: [],
  selectedWeapons: [],
  selectedArmor: "",
  hpMax: 10,
  hpCurrent: 0,
  mpMax: 20,
  mpCurrent: 0,
  momMax: 5,
  momCurrent: 0,
  attack: 0,
  accuracy: 0,
  dominance: 0,
  defense: 0,
  resolve: 0,
  resilience: 0,
  movement: 0,
  initiative: 0,
};
