const spells = [
  {
    name: "Fireball",
    description:
      "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame.",
    domain: "Evocation",
    school: "Arcane",
    category: "Offensive",
    damage: "8d6 fire damage",
    healing: "",
    effect: "Targets in a 20-foot radius must make a Dexterity saving throw",
    range: "150 feet",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Cure Wounds",
    description: "A creature you touch regains a number of hit points.",
    domain: "Evocation",
    school: "Divine",
    category: "Healing",
    damage: "",
    healing: "1d8 + spellcasting modifier",
    effect: "Restores hit points to target creature",
    range: "Touch",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Shield",
    description:
      "An invisible barrier of magical force appears and protects you.",
    domain: "Abjuration",
    school: "Arcane",
    category: "Defensive",
    damage: "",
    healing: "",
    effect: "+5 bonus to AC until the start of your next turn",
    range: "Self",
    casting: "1 reaction",
    duration: "1 round",
  },
  {
    name: "Magic Missile",
    description:
      "You create three glowing darts of magical force that automatically hit their targets.",
    domain: "Evocation",
    school: "Arcane",
    category: "Offensive",
    damage: "1d4+1 force damage per dart",
    healing: "",
    effect: "Creates 3 darts that automatically hit",
    range: "120 feet",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Invisibility",
    description: "A creature you touch becomes invisible until the spell ends.",
    domain: "Illusion",
    school: "Arcane",
    category: "Utility",
    damage: "",
    healing: "",
    effect: "Target becomes invisible",
    range: "Touch",
    casting: "1 action",
    duration: "Concentration, up to 1 hour",
  },
  {
    name: "Lightning Bolt",
    description:
      "A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose.",
    domain: "Evocation",
    school: "Arcane",
    category: "Offensive",
    damage: "8d6 lightning damage",
    healing: "",
    effect: "Targets must make a Dexterity saving throw",
    range: "Self (100-foot line)",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Healing Word",
    description:
      "A creature of your choice that you can see within range regains hit points.",
    domain: "Evocation",
    school: "Divine",
    category: "Healing",
    damage: "",
    healing: "1d4 + spellcasting modifier",
    effect: "Heals target creature at range",
    range: "60 feet",
    casting: "1 bonus action",
    duration: "Instantaneous",
  },
  {
    name: "Counterspell",
    description:
      "You attempt to interrupt a creature in the process of casting a spell.",
    domain: "Abjuration",
    school: "Arcane",
    category: "Defensive",
    damage: "",
    healing: "",
    effect: "Interrupts and negates enemy spellcasting",
    range: "60 feet",
    casting: "1 reaction",
    duration: "Instantaneous",
  },
  {
    name: "Haste",
    description:
      "Choose a willing creature that you can see within range. Until the spell ends, the target's speed is doubled.",
    domain: "Transmutation",
    school: "Arcane",
    category: "Buff",
    damage: "",
    healing: "",
    effect: "Doubles speed, grants extra action, +2 AC",
    range: "30 feet",
    casting: "1 action",
    duration: "Concentration, up to 1 minute",
  },
  {
    name: "Hold Person",
    description:
      "Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed.",
    domain: "Enchantment",
    school: "Arcane",
    category: "Control",
    damage: "",
    healing: "",
    effect: "Paralyzes humanoid target",
    range: "60 feet",
    casting: "1 action",
    duration: "Concentration, up to 1 minute",
  },
  {
    name: "Revivify",
    description:
      "You touch a creature that has died within the last minute. That creature returns to life with 1 hit point.",
    domain: "Necromancy",
    school: "Divine",
    category: "Healing",
    damage: "",
    healing: "Restores life, 1 HP",
    effect: "Resurrects recently deceased creature",
    range: "Touch",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Polymorph",
    description:
      "This spell transforms a creature that you can see within range into a new form.",
    domain: "Transmutation",
    school: "Arcane",
    category: "Utility",
    damage: "",
    healing: "",
    effect:
      "Transforms target into beast with CR equal to or less than target level",
    range: "60 feet",
    casting: "1 action",
    duration: "Concentration, up to 1 hour",
  },
  {
    name: "Meteor Swarm",
    description:
      "Blazing orbs of fire plummet to the ground at four different points you can see within range.",
    domain: "Evocation",
    school: "Arcane",
    category: "Offensive",
    damage: "20d6 fire damage and 20d6 bludgeoning damage",
    healing: "",
    effect: "Creates four 40-foot radius explosions",
    range: "1 mile",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Bless",
    description: "You bless up to three creatures of your choice within range.",
    domain: "Enchantment",
    school: "Divine",
    category: "Buff",
    damage: "",
    healing: "",
    effect: "Targets add 1d4 to attack rolls and saving throws",
    range: "30 feet",
    casting: "1 action",
    duration: "Concentration, up to 1 minute",
  },
  {
    name: "Eldritch Blast",
    description:
      "A beam of crackling energy streaks toward a creature within range.",
    domain: "Evocation",
    school: "Arcane",
    category: "Offensive",
    damage: "1d10 force damage",
    healing: "",
    effect: "Ranged spell attack",
    range: "120 feet",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Dispel Magic",
    description:
      "Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends.",
    domain: "Abjuration",
    school: "Arcane",
    category: "Utility",
    damage: "",
    healing: "",
    effect: "Ends magical effects on target",
    range: "120 feet",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Teleport",
    description:
      "This spell instantly transports you and up to eight willing creatures to a destination you select.",
    domain: "Conjuration",
    school: "Arcane",
    category: "Utility",
    damage: "",
    healing: "",
    effect: "Instantly transports creatures to distant location",
    range: "10 feet",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Power Word Kill",
    description:
      "You utter a word of power that can compel one creature you can see within range to die instantly.",
    domain: "Enchantment",
    school: "Arcane",
    category: "Offensive",
    damage: "Instant death if target has 100 HP or fewer",
    healing: "",
    effect: "Kills target with 100 HP or less",
    range: "60 feet",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Mass Heal",
    description:
      "A flood of healing energy flows from you into injured creatures around you.",
    domain: "Evocation",
    school: "Divine",
    category: "Healing",
    damage: "",
    healing: "Up to 700 HP distributed",
    effect: "Restores up to 700 hit points among creatures",
    range: "60 feet",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Wall of Fire",
    description: "You create a wall of fire on a solid surface within range.",
    domain: "Evocation",
    school: "Arcane",
    category: "Control",
    damage: "5d8 fire damage",
    healing: "",
    effect: "Creates barrier that damages creatures passing through",
    range: "120 feet",
    casting: "1 action",
    duration: "Concentration, up to 1 minute",
  },
];

module.exports = spells;
