module.exports = [
  {
    name: "Flamethrower",
    description:
      "Expel fire from your hands engulfing everything it touches in flames.",
    domain: "Ergomancy",
    school: "Temperature",
    category: "Damage",
    damage: "2d8",
    healing: "0",
    effect: "Burn",
    range: "30ft",
    casting: "Channel",
    duration: "Until ended or broken",
  },
  {
    name: "Frostspray",
    description:
      "Create a frost beam that chills and freezes everything it touches.",
    domain: "Ergomancy",
    school: "Temperature",
    category: "Damage",
    damage: "2d8",
    healing: "0",
    effect: "Freeze",
    range: "30ft",
    casting: "Channel",
    duration: "Until ended or broken",
  },
  {
    name: "Lightningbolt",
    description: "Strike and enemy down with an electric burst.",
    domain: "Ergomancy",
    school: "Electromagnetism",
    category: "Damage",
    damage: "2d8",
    healing: "0",
    effect: "Shock",
    range: "60ft",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Electric Field",
    description: "Protect yourself with a magnetic shield.",
    domain: "Ergomancy",
    school: "Electromagnestism",
    category: "Damage",
    damage: "0",
    healing: "0",
    effect: "Barrier",
    range: "5ft",
    casting: "Channel",
    duration: "Until ended or broken",
  },
  {
    name: "Shining Light",
    description:
      "The light pierces the eyes of all that look at it, impairing their vision.",
    domain: "Ergomancy",
    school: "Luminosity",
    category: "Bane",
    damage: "0",
    healing: "0",
    effect: "Blinded",
    range: "20ft",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Obscuring Shadow",
    description: "Shroud the area in darkness concealing all within it.",
    domain: "Ergomancy",
    school: "Luminosity",
    category: "Boon",
    damage: "0",
    healing: "0",
    effect: "Blinded",
    range: "20ft",
    casting: "Channel",
    duration: "Until ended or broken",
  },
  {
    name: "Force Shove",
    description: "Push an target up to 10ft away from you.",
    domain: "Animancy",
    school: "Psionic",
    category: "Damage",
    damage: "0",
    healing: "0",
    effect: "n/a",
    range: "20ft",
    casting: "1 action",
    duration: "Instantaneous",
  },
  {
    name: "Blood Claws",
    description:
      "Create claws of formed from flesh and bone. Each attack deals an additional 1d8. You take 1d4 damage when casting this spell.",
    domain: "Animancy",
    school: "Soma",
    category: "Damage",
    damage: "1d8",
    healing: "0",
    effect: "Bloodied",
    range: "Self",
    casting: "Channel",
    duration: "Until ended or broken",
  },
  {
    name: "Spirit Blade",
    description:
      "Form a spectral blade, that is seen only by you or another who can see souls. This blade deals 1d4 stamina damage.",
    domain: "Animancy",
    school: "Pnuema",
    category: "Damage",
    damage: "1d4",
    healing: "0",
    effect: "n/a",
    range: "Self",
    casting: "Channel",
    duration: "Until ended or broken",
  },
];
