export const PROFESSIONS = [
  "Warrior",
  "Knight",
  "Rogue",
  "Ranger",
  "Paladin",
  "Warlock",
  "Witch",
  "Wizard",
  "Sorcerer",
  "Magician",
  "Summoner",
  "Psychic",
];

export const AFFINITIES = [
  "Arcane",
  "Primal",
  "Divine",
  "Eldritch",
  "Blood",
  "Psionic",
  "Martial",
  "Chi",
];

export const CONDITIONS = [
  "blinded",
  "charmed",
  "deafened",
  "frightened",
  "grappled",
  "incapacitated",
  "invisible",
  "paralyzed",
  "petrified",
  "poisoned",
  "prone",
  "restrained",
  "stunned",
  "unconscious",
];

export const STATS = {
  ATTACK: "Attack",
  ACCURACY: "Accuracy",
  DOMINANCE: "Dominance",
  DEFENSE: "Defense",
  RESOLVE: "Resolve",
  RESILIENCE: "Resilience",
  MOVEMENT: "Movement",
  INITIATIVE: "Initiative",
  HP: "hp",
  HP_MAX: "hpMax",
  MP: "mp",
  MP_MAX: "mpMax",
  MOM: "mom",
  MOM_MAX: "momMax",
};

export const SKILLS = {
  ACROBATICS: "Acrobatics",
  ARCANA: "Arcana",
  ATHLETICS: "Athletics",
  CRAFTING: "Crafting",
  DECEPTION: "Deception",
  ENDURANCE: "Endurance",
  HISTORY: "History",
  INSIGHT: "Insight",
  INTIMIDATION: "Intimidation",
  INVESTIGATION: "Investigation",
  MEDICINE: "Medicine",
  NATURE: "Nature",
  PERCEPTION: "Perception",
  PERFORMANCE: "Performance",
  PERSUASION: "Persuasion",
  RELIGION: "Religion",
  LARCENY: "Larceny",
  STEALTH: "Stealth",
  SURVIVAL: "Survival",
  TACTICS: "Tactics",
  TAMING: "Taming",
  WARFARE: "Warfare",
};
